### ISSUE TITLE
the preScript doesn't work

### ISSUE THREAD

**Issue by stormzh** [axemclion/browser-perf#35]
I use a prescript for user log in and other web actions before the real action starts. Here is the variable options is defined:
```javascript
var options = {
    selenium: 'http://localhost:4444/wd/hub',
    browsers: ['chrome'],
    preScript: function preScr(browser) {
        return function(browser) {
            console.log('start prescript');
            \\...
              });
        }
    },
    actions: \\..
};
```
I noticed that the prescript is not executed. By debugging, I found that in lib\index.js, this is the order of the code:
```javascript
	}).then(function() {
		log('Session is ' + browser.sessionID);
		log('Running Prescript');
		return opts.preScript(browser);
	}).then(function() {
		if (url) {
			return browser.get(url);
		}
```
this means the browser will open the link after the prescript is executed which is wrong since the prescript needs the linked website to do the actions.  

FYI, I switched the order of the above code and confirmed the website is displayed before the preScript(browser). But I see the prescript code is still not called. Is there anything else missing?  Thanks a lot.

**Comment by axemclion** [comment]
@stormzh This order or execution was intentional, and the order of execution is 
1. The prescript would log in the user. Hence, it would have to navigate to a login url, and perform the login actions. This would typically set a cookie.
2. The url of the page to be tested is then navigated to. This would be a different URL than the page where the user was logged into. Note that we have still not started recording metrics.  
3. Finally, the page test starts - the `action` script runs. By default, this is scroll, but if you would like to measure page navigation, you would simply write a custom script to navigate to a page. 

- The reason why preScript is before URL navigation is because URL and login page may be different
- We would like to start render tests only after page nav because navigation causes a whole lot of paint events - this typically depends on what you really want to measure.

**Comment by axemclion** [comment]
For login specifcally, there is a `require(''browser-perf\lib/actions/loginAction.js')` that you could use. I could include a sample in the docs that logs into twitter and tests the feed page - will that help ?

**Comment by stormzh** [comment]
Thanks a lot, axemclion. I get your point. Here I need to make the change since our link is dynamically generated so we can set the homepage as the url and measure a specific action performance after logged in and some subsequent actions. I use my own preScriptFile and the customAction files. 

BTW, we need to update the API wiki page for the preScript sample by removing the out-most function, i.e. to be
```javascript
    preScript: function(browser) {
            console.log('start prescript');
```
I found the preScript code is called after I made the above change. Also can we update the preScriptFile element by giving an example, like:
```javascript
preScriptFile: 'c:/myPreScriptFile.js'
```
The "require" word in the current wiki page is kind of misleading since we don't use the keyword "require" here. 

I'm working on the last part of my code: output the performance counters into csv file. Do you have any suggestions on how to implement it? :)

**Comment by stormzh** [comment]
Thanks, axemclion. The issue is closed.
