### ISSUE TITLE
Timeline metrics highly inconsistent

### ISSUE THREAD

**Issue by kangax** [axemclion/browser-perf#46]
I'm pretty certain this has nothing to do with browser-perf, but I noticed that timeline metrics are very inconsistent. I wonder if anything can be done about that? (aside from running multiple tasks and getting a mean, which is obviously a super long process)

Here's an example of running the same page through browser-perf multiple times:

<img width="765" alt="screen shot 2015-11-11 at 4 08 38 pm" src="https://cloud.githubusercontent.com/assets/383/11094246/e51b51a0-888e-11e5-98d2-084ccf9e6a41.png">

Why are there such deviations? Layout ranges from 123 to 153; Paint from 40 to 44; function calls from ~4000 to ~7000. 

Any ideas?

**Comment by axemclion** [comment]
Would it be possible to share the automation script and the page that you are trying to test? If you have a lot of selenium scripts, they are also counted towards function calls - these function calls are run over a network which could be a big cause of inconsistencies. 

When a metric usually does not appear, it usually means that such an event did not occur on the timeline.

**Comment by axemclion** [comment]
Closing this issue - had a discussion on ways to make the metrics consistent. Some tips discussed were 

- Bootstrap the custom action and send it in one webdriver command instead of multiple commands since these commands are sent over the network
- Limit to collecting only one type of metric - specify the metric explicitly. 
- You can run diagnostics by setting the `DEBUG` environment variable to *. The logs thus collected should given an idea of what exactly is run. 


Please reopen if you still think this is an issue.
